CREATE ROLE app_users NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN PASSWORD 'app_users123';

GRANT CONNECT ON DATABASE postgres TO app_users;
GRANT USAGE ON SCHEMA tpl TO app_users;
GRANT SELECT ON ALL TABLES IN SCHEMA tpl TO app_users;

ALTER DEFAULT PRIVILEGES IN SCHEMA tpl
GRANT ALL ON TABLES TO app_users;

GRANT ALL ON TABLE tpl.addresses TO app_users;

ALTER DEFAULT PRIVILEGES
FOR USER app_users
IN SCHEMA tpl
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_users;

SELECT name, setting
FROM pg_settings WHERE name LIKE '%hba%';